BEGIN;
  CREATE TABLE IF NOT EXISTS users(
    id VARCHAR (255) UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR (255),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
  );
  CREATE INDEX on users(id);
COMMIT;
